require:
  - rubocop-performance
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  Exclude:
    - 'ui/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'db/**/*'
  NewCops: enable

### DISABLED

# http://rubocop.readthedocs.io/en/latest/cops_style/#styleconditionalassignment
Style/ConditionalAssignment:
  Enabled: false

# http://rubocop.readthedocs.io/en/latest/cops_style/#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false

# https://github.com/bbatsov/rubocop/blob/master/manual/cops_style.md#styleexpandpatharguments
Style/ExpandPathArguments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Naming/MethodParameterName:
  Enabled: false


Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
